name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

        env:
          REACT_APP_APIKEY: ${{ secrets.REACT_APP_APIKEY }}
          REACT_APP_AUTHDOMAIN: ${{ secrets.REACT_APP_AUTHDOMAIN }}
          REACT_APP_PROJECTID: ${{ secrets.REACT_APP_PROJECTID }}
          REACT_APP_STORAGEBUCKET: ${{ secrets.REACT_APP_STORAGEBUCKET }}
          REACT_APP_MESSAGINGSENDERID: ${{ secrets.REACT_APP_MESSAGINGSENDERID }}
          REACT_APP_APPID: ${{ secrets.REACT_APP_APPID }}
          REACT_APP_MEASUREMENTID: ${{ secrets.REACT_APP_MEASUREMENTID }}

      # Install and build the app
      - run: npm ci && npm run build

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TPSDATABASE_5E4F6 }}
          projectId: tpsdatabase-5e4f6
